// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/isAdmin": {
            "post": {
                "description": "По переданному user_id возвращает, является ли пользователь администратором",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Проверить админство пользователя",
                "parameters": [
                    {
                        "description": "ID пользователя",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.IsAdminSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.IsAdminRespSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request body"
                    },
                    "500": {
                        "description": "failed to check if user is admin"
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Возвращает роли авторизованного пользователя из токена доступа",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Получить роли текущего пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.GetUserRolesRespSchema"
                        }
                    },
                    "401": {
                        "description": "unauthorized"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Принимает refresh token, возвращает новый access и refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Обновить токены",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.RefreshSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.RefreshRespSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request body / failed to refresh token"
                    },
                    "500": {
                        "description": "unexpected error"
                    }
                }
            }
        },
        "/auth/signIn": {
            "post": {
                "description": "Возвращает токен доступа и токен обновления",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Авторизация",
                "parameters": [
                    {
                        "description": "Данные для авторизации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.LoginSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.LoginRespSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request body"
                    },
                    "401": {
                        "description": "invalid credentials"
                    },
                    "500": {
                        "description": "failed to log in"
                    }
                }
            }
        },
        "/auth/signUp": {
            "post": {
                "description": "Возвращает ID пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Зарегистрировать пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.RegisterSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.RegisterRespSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request body"
                    },
                    "409": {
                        "description": "user with same login already exists"
                    },
                    "500": {
                        "description": "failed to register user"
                    }
                }
            }
        },
        "/detokenize": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Принимает токен, ищет соответствующий mapping и возвращает исходный plaintext",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokenizer"
                ],
                "summary": "Детокенизация",
                "parameters": [
                    {
                        "description": "Токен для детокенизации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.DetokenizeSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.DetokenizeRespSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request body / invalid arguments"
                    },
                    "404": {
                        "description": "token not found / token expired"
                    },
                    "500": {
                        "description": "failed to detokenize / unexpected error"
                    }
                }
            }
        },
        "/kinds": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список видов данных",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kinds"
                ],
                "summary": "Получить список видов данных",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.KindSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to get kind list"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создает новый вид данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kinds"
                ],
                "summary": "Создать вид данных",
                "parameters": [
                    {
                        "description": "Данные вида данных",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.CreateKindSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.KindSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request"
                    },
                    "409": {
                        "description": "kind already exists"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            }
        },
        "/kinds/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает объект вида данных",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kinds"
                ],
                "summary": "Получить вид данных по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID вида данных",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.KindSchema"
                        }
                    },
                    "400": {
                        "description": "invalid kind ID"
                    },
                    "404": {
                        "description": "kind not found"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет вид данных по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kinds"
                ],
                "summary": "Удалить вид данных",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID вида данных",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid kind ID"
                    },
                    "404": {
                        "description": "kind not found"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает обновленный вид данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kinds"
                ],
                "summary": "Обновить вид данных",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID вида данных",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UpdateKindSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.KindSchema"
                        }
                    },
                    "400": {
                        "description": "invalid kind ID"
                    },
                    "404": {
                        "description": "kind not found"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            }
        },
        "/mappings/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список маппингов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Получить список маппингов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.MappingSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to get mapping list"
                    }
                }
            }
        },
        "/mappings/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает объект маппинга",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Получить маппинг по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID маппинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.MappingSchema"
                        }
                    },
                    "400": {
                        "description": "invalid token ID"
                    },
                    "404": {
                        "description": "mapping not found"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет объект маппинга по ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Удалить маппинг по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID маппинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid token ID"
                    },
                    "401": {
                        "description": "unauthorized"
                    },
                    "404": {
                        "description": "mapping not found"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает объект маппинга",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mappings"
                ],
                "summary": "Обновить маппинг по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID маппинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UpdateMappingSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.MappingSchema"
                        }
                    },
                    "400": {
                        "description": "invalid token ID"
                    },
                    "404": {
                        "description": "mapping not found"
                    },
                    "500": {
                        "description": "internal error"
                    }
                }
            }
        },
        "/tokenize": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Принимает plaintext и параметры токенизации, возвращает созданный токен и метаданные.\nРежим \"pseudonymize\" — обратимая операция, mapping сохраняется и его можно детокенизировать.\nРежим \"anonymize\" — необратимая операция, mapping нигде не сохраняется,\nответом является schemas.TokenizeResultSchema, такой токен нельзя детокенизировать.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokenizer"
                ],
                "summary": "Токенизация",
                "parameters": [
                    {
                        "description": "Данные для токенизации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.TokenizeSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mode=anonymize",
                        "schema": {
                            "$ref": "#/definitions/schemas.TokenizeResultSchema"
                        }
                    },
                    "400": {
                        "description": "invalid request body / invalid arguments"
                    },
                    "409": {
                        "description": "token already exists"
                    },
                    "500": {
                        "description": "failed to tokenize / unexpected error"
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.CreateKindSchema": {
            "type": "object",
            "properties": {
                "access_level": {
                    "type": "integer",
                    "example": 3
                },
                "mask": {
                    "type": "string",
                    "example": "^\\d{4} \\d{6}$"
                },
                "name": {
                    "type": "string",
                    "example": "passport"
                },
                "russian_name": {
                    "type": "string",
                    "example": "Паспорт"
                },
                "short_name": {
                    "type": "string",
                    "example": "psp"
                }
            }
        },
        "schemas.DetokenizeRespSchema": {
            "type": "object",
            "properties": {
                "plaintext": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "schemas.DetokenizeSchema": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "schemas.GetUserRolesRespSchema": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.RoleSchema"
                    }
                }
            }
        },
        "schemas.IsAdminRespSchema": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "schemas.IsAdminSchema": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "schemas.KindSchema": {
            "type": "object",
            "properties": {
                "access_level": {
                    "type": "integer",
                    "example": 3
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "mask": {
                    "type": "string",
                    "example": "^\\d{4} \\d{6}$"
                },
                "name": {
                    "type": "string",
                    "example": "passport"
                },
                "russian_name": {
                    "type": "string",
                    "example": "Паспорт"
                },
                "short_name": {
                    "type": "string",
                    "example": "psp"
                }
            }
        },
        "schemas.LoginRespSchema": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.RoleSchema"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "schemas.LoginSchema": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "schemas.MappingSchema": {
            "type": "object",
            "properties": {
                "cipher_text": {
                    "type": "string",
                    "example": "rfAsPo1N0a3cBiELOlgmHUXS5Q=="
                },
                "created_at": {
                    "type": "string",
                    "example": "2006-01-02T15:04:05Z07:00"
                },
                "dek_wrapped": {
                    "type": "string",
                    "example": "dmF1bHQ6djE6dTZCY0lXRURFOG..."
                },
                "deterministic": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "kind": {
                    "$ref": "#/definitions/schemas.KindSchema"
                },
                "token": {
                    "type": "string",
                    "example": "fio_7f82a1c3"
                },
                "token_ttl": {
                    "type": "string",
                    "example": "24h0m0s"
                }
            }
        },
        "schemas.RefreshRespSchema": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "schemas.RefreshSchema": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "schemas.RegisterRespSchema": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                }
            }
        },
        "schemas.RegisterSchema": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "schemas.RoleSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schemas.TokenizeResultSchema": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "fio_7f82a1c3"
                }
            }
        },
        "schemas.TokenizeSchema": {
            "type": "object",
            "properties": {
                "deterministic": {
                    "type": "boolean"
                },
                "kind_id": {
                    "type": "integer"
                },
                "mode": {
                    "description": "\"pseudonymize\" | \"anonymize\"",
                    "type": "string",
                    "example": "pseudonymize"
                },
                "plaintext": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "token_ttl": {
                    "type": "integer"
                }
            }
        },
        "schemas.UpdateKindSchema": {
            "type": "object",
            "properties": {
                "access_level": {
                    "type": "integer",
                    "example": 3
                },
                "mask": {
                    "type": "string",
                    "example": "^\\d{4} \\d{6}$"
                },
                "name": {
                    "type": "string",
                    "example": "passport"
                },
                "russian_name": {
                    "type": "string",
                    "example": "Паспорт"
                },
                "short_name": {
                    "type": "string",
                    "example": "psp"
                }
            }
        },
        "schemas.UpdateMappingSchema": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Anonix Gateway API",
	Description:      "Описание эндпоинтов сервиса анонимизации данных",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
